### ISSUE TITLE
"A non-IMessage field was encountered" error

### ISSUE THREAD

**Issue by StevenBegin** [googleads/google-ads-dotnet#533]
A Google Ads API Forum Advisor has responded to [my post](https://groups.google.com/g/adwords-api/c/s8zcR1Yu3tQ) advising that they believe it _“seems that the .NET client library is possibly the reason behind the Inner Exception 1: ArgumentException: error.  I recommend you to consult the implementation with .NET client library owner as they are appropriate to provide insights on data retrieved and getting above mentioned errors.”_

I am running the code from a Windows (10) machine running .NET 6.0 (we are in Test mode). 

The nature of the problem we are experiencing is that - in using the latest .NET sample code for [getting GoogleAds Change Details (V14)](https://developers.google.com/google-ads/api/samples/get-change-details) - it works as expected (i.e., without an error since it's the exact sample code) for only 65 of 114 active client customers. 

May you please assist regarding what can be done since - for the other 49 client customers - the sample code errors upon attempting to retrieve change details because it encounters the following type of “non-IMessage field” error?

_“Inner Exception 1: ArgumentException: Cannot retrieve field value. A non-IMessage field was encountered after navigating keyword.match_type upto keyword.”_

During some analysis, I found eight variations of change fields this non-IMessage field happened regarding. 

One variation had fifteen (15) of the errors. They were similar “non-IMessage field” errors, except were **"Cannot retrieve field value. A non-IMessage field was encountered after navigating manual_cpc.enhanced_cpc_enabled upto manual_cpc"**. These came via the following nine (9) Request IDs:
 

- -VGrm3_Ib4Udoo1NUQU0dQ
- _0ZCK8I_-CN5Fi_vzohsxQ
- 109YbJlU6SC6EuBt0nNRzA
- DXSSxjFCZ-7tPrWacbizfQ
- EmbI0CXTS9PyY2xpcoUhNA
- hvVQAa27BRQ7NwcOs9jcJQ
- Lg0f_NpQN76OIBUuIk4PeA
- Pjt8vO_XxI4o0Iya7_hbUg
- XDUPNC4GwZyqEegZMuhQCg

 
… All fifteen were changes the API response confirmed were initiated using the GoogleAdsWebClient.

**I have attached a text file showing the correct below-mentioned snytax because I cannot seem to get it to render with the backslash for the non-errant below, etc. in this Issue-submission GUI.** 

When I looked at examples of that kind(/field) of errant response result (i.e., one GoogleAds Row in the response), 8 of the 15 had syntax in the result as follows:
•	…ChangedFields":{"Paths":["manual_cpc.enhanced_cpc_enabled","maximize_conversions.target_cpa_micros"]},"Campaign" …

The other 7 of these 15 had errant results with syntax as follows:
•	...ChangedFields":{"Paths":["manual_cpc.enhanced_cpc_enabled"]},"Campaign":...

When I look to an acceptable (non-errant) change event that also had this “manual_cpc.enhanced_cpc_enabled”, I found its result had syntax as shown in the attached text file (i.e., like the 7 of 15, but with several backslashes).

### Questions:

1.	Is the non-errant syntax (with the backslash) the only syntax that the .NET code owners believe is the properly-formed data received from the GoogleAds API, whereas the other two (in red) do not follow an expectation? 
2.	If so (for the first question's answer), where did that expectation come from (e.g., within GoogleAds documentation)?
3.	If not, and all three forms should be acceptable, can an adjustment be made within the .NET sample code to handle these appropriately without an error?
4.	Lastly, since this is only one type of non-IMessage data being encountered, can a solution be employed for this as well as the others (I have encountered at least seven others involving other change fields)?

- manual_cpc_enhanced_cpc_enabled upto manual_cpc.
- maximize_conversions_target_cpa_micros upto maximize_conversions.
- responsive_display_ad_long_headline_text upto responsive_display_ad.long_headline.
- target_spend_cpc_bid_ceiling_micros upto target_spend.
- target_cpa_target_cpa_micros upto target_cpa.
- target_impression_share_cpc_bid_ceiling_micros upto target_impression_share.
- target_impression_share_location upto target_impression_share.
- target_impression_share_location_fraction_micros upto target_impression_share

I hope I have provided what is needed, but please let me know if more information is necessary.

Thank you!
[manual_cpc.txt](https://github.com/googleads/google-ads-dotnet/files/12441713/manual_cpc.txt)

**Comment by Raibaz** [comment]
There have been some issues with change history and change events in the API in the past few days, it may be the reason why you are not able to retrieve your data correctly from the API.

The issues have been resolved now, so can you please try again in a few days' time to see if you are still experiencing the issue?

Thanks and sorry for the inconvenience

**Comment by StevenBegin** [comment]
Thank you for your follow up on this. 

Unfortunately, it does seem to still be happening. For example, six change items just impacted (for request ID N7hVnTJHdTp3-AEb1I19ww which was processed between 2023-08-28 19:36:31.707 UTC and 2023-08-28 19:36:32.807 UTC) were as follow:

•	"Cannot retrieve field value. A non-IMessage field was encountered after navigating maximize_conversions.target_cpa_micros upto maximize_conversions." (happened twice)
•	"Cannot retrieve field value. A non-IMessage field was encountered after navigating target_impression_share.location_fraction_micros upto target_impression_share."
•	"Cannot retrieve field value. A non-IMessage field was encountered after navigating target_impression_share.location upto target_impression_share."
•	"Cannot retrieve field value. A non-IMessage field was encountered after navigating target_impression_share.cpc_bid_ceiling_micros upto target_impression_share."
•	"Cannot retrieve field value. A non-IMessage field was encountered after navigating responsive_display_ad.long_headline.text upto responsive_display_ad.long_headline."

**Comment by StevenBegin** [comment]
Thank you! I appreciate your verification, and all your work on this.

**Comment by StevenBegin** [comment]
The last "Cannot retrieve field value. A non-IMessage field was encountered" type of error we received was for RequestID qqNqE8AgmNa6mXQzyjfs1A and was at 2023-08-30 16:35:43.430Z

However, unfortunately, now we are not even able to get as far as where that error was happening to confirm it would be resolved. This is because for any new ChangeEvent, the FieldMaskPath navigation attempt now actually immediately errors out with "Nullable object must have a value" and so it disallows navigation toward collecting changeEvent item data.

This happened between 2023-08-31 17:47:12.517Z and 2023-08-31 17:58:36.507Z for the following 20 RequestIDs:

•	0E1uXFKPULIu-XoaoWp6OQ
•	48s0cblMXdhKMv-syfWavQ
•	4sPMHP-j0Xfe6G3jDIgvVw
•	bmcztLFaK3_90BlTpAVv1Q
•	F2lKKFzsiRAw635NatKnhg
•	fd6OmcOZgBqAv4011pJ0jg
•	Gt0EVU748udeG6SyygYuGw
•	Ipvvf3ZzRwbt0fuhhWwvJQ
•	j3j8oI0cNaOExe2AKOCvzA
•	l7xPk00MFbNJOxM43Gxo-g
•	LQdEf5eWUNy1THcaK-VPCg
•	Mc70fCQ4_B3B9w7Q_9rNpw
•	ObV19xWLoRMjJnQswbmWdA
•	pZ4_beuKO5qFa_NkeiEO2A
•	RTNli-cJ-_bwB16-r6BsqA
•	S8aKX0uD0R8-bOz5GDl09g
•	t2UZeZbsRU2kuznvylTISg
•	XjMTab-bhi-zDnxTur6UBw
•	XY9cr2nowln3OSLYUmuNiQ
•	zEE4kne2UWAmpGrmrOsx-w

I was not sure whether this should be reported as a bug in issue #[534](https://github.com/googleads/google-ads-dotnet/pull/534) that my issue ended up associated to, or reported in my issue #[533 ](https://github.com/googleads/google-ads-dotnet/pull/533)that I have not been able to confirm is resolved yet, or in a new issue altogether.

May you please let me know if I should report this differently, and what can be done to resolve this as well as for me to then be enabled to confirm the IMessage-related issue #533 has been resolved?

**Comment by StevenBegin** [comment]
I am still encountering the same problem reported in this issue [#533](https://github.com/googleads/google-ads-dotnet/pull/533).

**Comment by Raibaz** [comment]
Are you using the code we recently merged to the `main` branch? I have just tried running the GetChangeDetails example and it executes successfully.

**Comment by StevenBegin** [comment]
My code is based off of what I see in Main for GetChangeDetails which says it has not changed since June 08, 2023. 

I am looking at ...

https://github.com/googleads/google-ads-dotnet/blob/main/Google.Ads.GoogleAds/examples/AccountManagement/GetChangeDetails.cs

I have also found it at:

https://developers.google.com/google-ads/api/samples/get-change-details

Is there a different place I should be looking?

**Comment by Raibaz** [comment]
Ah, I see.

The fix I merged is in the FieldMasks class, and we haven't published a release that contains the change yet.

I'm planning to publish a release next week.

**Comment by Raibaz** [comment]
I just released v17.0.1, you should be able to use it now.

**Comment by StevenBegin** [comment]
Should the GetChangeDetails code (still on V14) pick it up automatically (by virtue of its reference to it)? 

For dotnet, I am not seeing FieldMasks available directly; it's a 404 (https://developers.google.com/google-ads/api/docs/client-libs/dotnet/fieldmasks).

When I run the same GetChangeDetails (V14), I am still getting the error (e.g., requestID UrJc6q5toMaJT0IUw4qpOw "Cannot retrieve field value. A non-IMessage field was encountered after navigating target_impression_share.location_fraction_micros upto target_impression_share." at 2023-09-05 14:59:57.000).

**Comment by Raibaz** [comment]
That depends on how you are running the examples; if you are including the Google.Ads.GoogleAds PackageReference in your project, you need to update it to version 17.0.1 to see the bugfix.

**Comment by StevenBegin** [comment]
Thank you; I _did_ have that NuGet package 17.0.0; I have now updated it to the 17.0.1 where you've made the bug fix. So far no repeated error. I will watch it a little while longer. Thanks again for your quick work on this!
